# Generated by Django 3.0.5 on 2020-08-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order_orderproduct_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
    ]
